# Generated by Django 5.1.1 on 2024-09-25 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invetario', '0002_rename_nome_produto_nome_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='unidade_venda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invetario.unidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='produtos_categoria',
            field=models.ManyToManyField(blank=True, related_name='produtos', to='invetario.produto'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='produtos_unidade',
            field=models.ManyToManyField(blank=True, to='invetario.produto'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
