# Generated by Django 5.1.1 on 2024-09-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='img',
            field=models.ImageField(default=1, upload_to='perfil/%Y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
