# Generated by Django 5.1.1 on 2024-09-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_login', '0004_usuario_delete_imageprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/%Y'),
        ),
    ]
